# Proyecto Integrador
## Tecnológico de Monterrey
### Maestría en Inteligencia Artificial Aplicada (MNA)
#### Equipo 7
* Jorge Arturo Federico Rivera – A01250724
* Marco Antonio Vázquez Morales – A01793704 
* Alejandro Jesús Vázquez Navarro - A01793146

### Install libraries for Colab

In [ ]:
%pip install matplotlib-venn sweetviz ydata-profiling
%pip install --upgrade Pillow

### Import libraries

In [1]:
import pandas as pd
import sweetviz as sv
from ydata_profiling import ProfileReport

### Read data from Excel databases

#### base_multimorb_fase1_fase_2_clinicas_originales.xlsx

In [19]:
cols_to_include = [
    "id",
    "ev_1ertrim",
    "ev_dieta",
    "biopsias",
    "estado",
    "edad_dx",
    "peso_pg_h",
    "talla",
    "imc_h",
    "obs_h",
    "peso_1",
    "peso_2",
    "peso_3",
    "gluc_dx_0",
    "gluc_dx_60",
    "gluc_dx_120",
    "gluc_dx_180",
    "dx_inicio",
    "auc",
    "ichos_pregesta",
    "hta_pregesta",
    "sop",
    "hipotiroidismo",
    "hipertiroidismo",
    "consumo_alcohol",
    "consumo_tabaco",
    "anticonceptivo",
    "ah_dm",
    "ah_hta",
    "ah_ob",
    "ah_dg",
    "no_gestas",
    "ant_dg",
    "ant_aborto",
    "ant_obito",
    "ant_mnt",
    "ant_malformado",
    "ant_macrosomico",
    "cesarea_iter",
    "ema",
    "alta_paridad",
    "estatura_baja",
    "pgr",
    "infeccion_pregesta",
    "embarazo_multiple",
    "preeclampsia",
    "polihidramnios",
    "hidramnios",
    "infeccion_gesta",
    "ac_fol_pregesta",
    "ac_fol_gesta",
    "sdg_fol",
    "trim_fol",
    "ac_fol_dosis_mg",
    "modo_parto",
    "sdg_parto",
    "termino_rn",
    "macrosomia_rn",
    "malformaciones_rn",
    "aborto_rn",
    "obito_rn",
    "mnt_rn",
    "ins_dx",
    "gluc_dx",
    "crea_dx",
    "urico_dx",
    "tg_dx",
    "ct_dx",
    "hdl_dx",
    "ldl_dx",
    "apob_dx",
    "lep_dx",
    "adipo_dx",
    "pcr_dx",
    "tiene_pareja",
    "paciente_trabaja",
    "puntos_ses",
    "nivel_ses",
    "trimestre_ev1",
    "AcFolico_supl",
    "AcFolico_marca",
    "AcFsup_dosis_mg",
    "supl_preconcep",
    "supl_1erTrim",
    "Multi0_acfol1",
    "iniciosupl_sdg",
    "AcFolico_papa",
    "Ins_1av",
    "Gluc_1av",
    "Col_1av",
    "Tg_1av",
    "LDL_1av",
    "HDL_1av",
    "CMB_1av",
    "PCT_1av",
    "CMB_2av",
    "PCT_2av",
]

excel_file_1 = "data/base_multimorb_fase1_fase_2_clinicas_originales.xlsx"

df1_sheet1 = pd.read_excel(
    excel_file_1,
    sheet_name=0,
    usecols=cols_to_include,
)

df1_sheet2 = pd.read_excel(
    excel_file_1,
    sheet_name=1,
    usecols=cols_to_include,
)

df1_sheets = [
    df1_sheet1,
    df1_sheet2
]

df1 = pd.concat(df1_sheets)

df1.describe()

,ev_1ertrim,ev_dieta,biopsias,estado,edad_dx,peso_pg_h,talla,imc_h,obs_h,peso_1,...,AcFolico_papa,Ins_1av,Gluc_1av,Col_1av,Tg_1av,LDL_1av,HDL_1av,CMB_1av,CMB_2av,PCT_2av
count,1335.000000,1335.000000,1228.000000,1250.000000,1314.000000,1237.000000,1292.000000,1225.000000,1290.000000,610.000000,...,277.000000,29.000000,209.000000,209.000000,209.000000,207.000000,208.000000,211.000000,154.000000,154.000000
mean,0.158801,0.183521,0.084691,0.580800,30.909437,64.207672,1.562417,26.322959,0.193798,64.584393,...,0.050542,10.396552,85.119617,182.193301,147.655024,88.697585,60.486538,29.089573,28.700325,26.356818
std,0.369706,0.387238,0.278534,0.644208,6.832353,13.094585,0.061308,5.137912,0.395426,12.576272,...,0.219456,7.009967,6.647010,132.250206,55.816291,40.751169,18.224425,4.041969,4.155021,6.387703
min,0.000000,0.000000,0.000000,0.000000,15.000000,35.000000,1.250000,16.560653,0.000000,37.500000,...,0.000000,0.000000,68.000000,79.000000,52.000000,36.600000,31.000000,21.000000,3.500000,7.500000
25%,0.000000,0.000000,0.000000,0.000000,26.000000,55.000000,1.520000,22.826881,0.000000,55.825000,...,0.000000,6.400000,81.000000,151.000000,109.000000,68.000000,48.000000,26.400000,26.500000,22.500000
50%,0.000000,0.000000,0.000000,0.000000,32.000000,62.000000,1.560000,25.476660,0.000000,63.000000,...,0.000000,8.900000,84.000000,172.000000,143.000000,85.000000,57.000000,28.700000,29.000000,26.500000
75%,0.000000,0.000000,0.000000,1.000000,36.000000,70.000000,1.600000,28.959000,0.000000,71.650000,...,0.000000,12.600000,88.000000,194.000000,175.000000,102.500000,69.250000,31.500000,31.000000,30.500000
max,2.000000,1.000000,1.000000,2.000000,48.000000,140.000000,1.750000,60.595568,1.000000,119.000000,...,1.000000,32.600000,115.000000,1995.000000,349.000000,477.000000,137.000000,48.800000,39.000000,48.500000

In [20]:
df1.head(10)

,id,ev_1ertrim,ev_dieta,biopsias,estado,edad_dx,peso_pg_h,talla,imc_h,obs_h,...,Ins_1av,Gluc_1av,Col_1av,Tg_1av,LDL_1av,HDL_1av,CMB_1av,PCT_1av,CMB_2av,PCT_2av
0,GD01,0.0,0.0,0.0,1.0,32.0,55.0,1.59,21.755469,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GD04,0.0,0.0,0.0,1.0,39.0,60.0,1.50,26.666667,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GD05,0.0,0.0,0.0,1.0,37.0,85.0,1.61,32.791945,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GD06,0.0,0.0,0.0,1.0,28.0,45.0,1.55,18.730489,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GD07,0.0,0.0,0.0,1.0,40.0,82.0,1.55,34.131113,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,GD09,0.0,0.0,0.0,1.0,37.0,75.0,1.63,28.228386,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,GD010,0.0,0.0,0.0,1.0,40.0,80.0,1.64,29.744200,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,GD011,0.0,0.0,0.0,1.0,39.0,60.0,1.51,26.314635,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,GD012,0.0,0.0,0.0,1.0,26.0,49.0,1.51,21.490286,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,GD013,0.0,0.0,0.0,1.0,34.0,75.0,1.60,29.296875,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df1.tail(10)

,id,ev_1ertrim,ev_dieta,biopsias,estado,edad_dx,peso_pg_h,talla,imc_h,obs_h,...,Ins_1av,Gluc_1av,Col_1av,Tg_1av,LDL_1av,HDL_1av,CMB_1av,PCT_1av,CMB_2av,PCT_2av
172,HG294,1.0,1.0,NaN,NaN,26.0,76.0,1.71,25.990903,0.0,...,NaN,88.0,221.0,273.0,107.4,59.0,29.1,30,NaN,NaN
173,HG295,1.0,1.0,NaN,NaN,39.0,70.0,1.58,28.040378,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,32.0,34.5,NaN,NaN
174,HG296,1.0,1.0,NaN,0.0,32.0,60.0,1.62,22.862369,0.0,...,NaN,70.0,266.0,69.0,99.2,53.0,28.0,18.75,NaN,NaN
175,HG297,1.0,1.0,NaN,NaN,37.0,64.0,1.65,23.507805,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,26.5,30.5,NaN,NaN
176,HG298,1.0,1.0,NaN,NaN,30.0,89.0,1.72,30.083829,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,36.5,37,NaN,NaN
177,HG299,1.0,1.0,NaN,NaN,25.0,45.0,1.51,19.735976,0.0,...,0.0,79.0,149.0,52.0,73.6,65.0,NaN,NaN,NaN,NaN
178,HG300,1.0,1.0,NaN,NaN,33.0,80.0,1.56,32.873110,1.0,...,0.0,92.0,204.0,109.0,119.2,63.0,32.0,42.5,NaN,NaN
179,HG301,1.0,1.0,NaN,0.0,26.0,62.0,1.56,25.476660,0.0,...,0.0,88.0,135.0,93.0,NaN,56.0,24.0,23,NaN,NaN
180,HG302,1.0,1.0,NaN,0.0,15.0,48.0,1.60,18.750000,0.0,...,NaN,88.0,132.4,66.9,NaN,NaN,23.5,22.5,NaN,NaN
181,HG303,1.0,1.0,NaN,NaN,21.0,54.0,1.72,18.253110,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,24.2,15.5,NaN,NaN

##### Remover columnas no útiles

In [ ]:
cols_to_remove = [
    "id_gdg",
    "id",
    "nombre",
    "registro",
    "hoja_datos",
    "exclusion",
    "ev_1ertrim",
    "ev_dieta",
    "biopsias",
    "comentario",
    "hospital_ref",
    "0_pp",
    "60_pp",
    "120_pp",
    "180_pp",
    "peso_placenta",
    "fur",
    "fecha_encuesta",
    "fecha_muestra",
    "sdg_muestra",
    "ins_madre_parto",
    "gluc_madre_parto",
    "tg_madre_parto",
    "ct_madre_parto",
    "hdl_madre_parto",
    "ldl_madre_parto",
    "ins_cordon_parto",
    "gluc_cordon_parto",
    "tg_cordon_parto",
    "ct_cordon_parto",
    "hdl_cordon_parto",
    "ldl_cordon_parto",
    "ins_pp",
    "gluc_pp",
    "crea_pp",
    "urico_pp",
    "tg_pp",
    "ct_pp",
    "hdl_pp",
    "ldl_pp",
    "apob_pp",
    "lep_pp",
    "adipo_pp",
    "pcr_pp",
    "no_cuartos",
    "no_baños",
    "regadera",
    "no_focos",
    "piso_hogar",
    "no_autos",
    "no_tv",
    "no_computador",
    "estufa",
    "estudio_max",
    "puntos_ses",
    "domicilio",
    "telefono",
    "Fecha_ev1",
    "SDG_ev1",
    "trimestre_ev1",
]

# TODO

##### ydata-profiling

In [24]:
profile1 = ProfileReport(
    df1,
    title="Minimal Profiling Report for df1",
    # explorative=True,
    minimal=True,
)
profile1.to_file("data/reports/profile1_min_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [1]:
# profile1.to_notebook_iframe()

In [25]:
profile1_exp = ProfileReport(
    df1,
    title="Explorative Profiling Report for df1",
    explorative=True,
    # minimal=True,
)
profile1_exp.to_file("data/reports/profile1_exp_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

/home/deck/Documents/School/Proyecto Integrador/Repositorio/MNA_ProyectoIntegrador-Equipo7/.venv/lib/python3.11/site-packages/ydata_profiling/model/correlations.py:66: UserWarning: There was an attempt to calculate the auto correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"auto": {"calculate": False}})`
If this is problematic for your use case, please report this as an issue:
https://github.com/ydataai/ydata-profiling/issues
(include the error message: 'cannot reindex on an axis with duplicate labels')
  warnings.warn(
/home/deck/Documents/School/Proyecto Integrador/Repositorio/MNA_ProyectoIntegrador-Equipo7/.venv/lib/python3.11/site-packages/seaborn/matrix.py:260: FutureWarning: Format strings passed to MaskedConstant are ignored, but in future may error or produce different behavior
  annotation = ("{:" + self.fmt + "}").format(val)
/home/deck/Documents/School/Proyecto Integrador/Repositorio/MNA_ProyectoIntegrador-Equipo7/.venv/lib/python3.11/site-packages/ydata_profiling/model/missing.py:78: UserWarning: There was an attempt to generate the Heatmap missing values diagrams, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(missing_diagrams={"Heatmap": False}`)
If this is problematic for your use case, please report this as an issue:
https://github.com/ydataai/ydata-profiling/issues
(include the error message: 'could not convert string to float: '--'')
  warnings.warn(

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

##### sweetviz

In [34]:
"""
    Posibles target_feat indicados:
        modo_parto
        sdg_parto
        termino_rn
        macrosomia_rn
"""

sv_df1 = df1.copy()

sv_df1 = sv_df1.astype(
    {
#         "registro": "str",
#         "fur": "str", # fecha
#         "fecha_encuesta": "str", # fecha
#         "fecha_muestra": "str", # fecha
#         "Fecha_ev1": "str", # fecha
        "AcFolico_marca": "str", # nombre
#         "f_encCTOG": "str", # fecha
#         "fecha_muestraCTOG": "str" # fecha
    },
    copy=False
)

cols_to_numeric = [
#     "sdg_dx",
#     "gluc_pp_60",
    "ant_macrosomico",
#     "sexo_rn",
#     "peso_rn",
#     "talla_rn",
#     "pc",
#     "capurro",
#     "apgar_1",
#     "apgar_5",
#     "pH_A",
#     "pO2_A",
#     "pCO2_A",
#     "pH_V",
#     "pO2_V",
#     "pCO2_V",
    "macrosomia_rn",
#     "percentil_peso",
#     "peso_placenta",
#     "ins_cordon_parto",
#     "e2_cordon_parto",
#     "lep_cordon_parto",
#     "adipo_cordon_parto",
#     "ins_pp",
#     "gluc_pp",
#     "crea_pp",
#     "urico_pp",
#     "tg_pp",
#     "ct_pp",
#     "hdl_pp",
#     "ldl_pp",
#     "apob_pp",
#     "lep_pp",
#     "adipo_pp",
#     "pcr_pp",
#     "pgn_pp",
#     "e2_pp",
#     "SDG_ev1",
#     "Folato_R24Hmcg",
#     "FFQ_FOLATOmcg",
#     "FFQ_DFE",
#     "FFQ_energia",
#     "AcFolico_supl",
    "AcFsup_dosis_mg",
    "PCT_1av",
#     "DFE_R24H2",
]

for col in cols_to_numeric:
    sv_df1[col] = pd.to_numeric(sv_df1[col], errors="coerce")

report1 = sv.analyze(
    sv_df1,
    # target_feat="termino_rn", # comentando porque hay que eliminar NA"s primero
    pairwise_analysis="on", # apagando porque sv se queja en modo auto 
    # verbosity="progress_only", # no funciona todavía?
)

                                             |          | [  0%]   00:00 -> (? left)

In [35]:
report1.show_html(
    filepath="data/reports/sv_report1.html",
    open_browser=False,
)

Report data/reports/sv_report1.html was generated.

In [ ]:
# report1.show_notebook()

#### base_metabolicos_geneticos

In [10]:
excel_file_2 = "data/base_metabolicos_geneticos.xlsx"

df2 = pd.read_excel(
    excel_file_2,
    sheet_name=0,
)

df2.describe()

,ast_pv,alt_pv,crea_pv,homo_pv,vb12_pv,acfol_pv,ast_dx,alt_dx,crea_dx,homo_dx,...,PC4,PC5,PC6,PC7,PC8,PC9,PC10,_merge,aim_118,aim_32
count,0.0,0.0,25.000000,25.000000,25.000000,25.000000,135.000000,133.000000,256.000000,588.000000,...,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1006.000000,1023.000000,1023.000000,1023.000000
mean,NaN,NaN,0.571600,6.875200,352.840000,27.780000,15.570370,11.052632,0.650352,7.720731,...,0.000092,-0.001400,-0.002408,0.000771,0.000467,-0.000146,-0.000568,2.966764,0.983382,0.076246
std,NaN,NaN,0.084591,1.681128,92.053734,9.309896,9.310194,7.121580,0.151733,2.774743,...,0.019938,0.020758,0.019974,0.020797,0.021150,0.021143,0.020628,0.255794,0.127897,0.265522
min,NaN,NaN,0.440000,4.040000,222.000000,9.300000,1.000000,0.000000,0.280000,3.900000,...,-0.054300,-0.073900,-0.062600,-0.062100,-0.066100,-0.080700,-0.068700,1.000000,0.000000,0.000000
25%,NaN,NaN,0.520000,5.960000,275.000000,21.300000,8.500000,7.000000,0.540000,5.820000,...,-0.013600,-0.014575,-0.015700,-0.012975,-0.013700,-0.013825,-0.013875,3.000000,1.000000,0.000000
50%,NaN,NaN,0.560000,6.480000,333.000000,27.700000,15.000000,9.000000,0.660000,7.050000,...,-0.001950,-0.002100,-0.002400,-0.000800,-0.001100,-0.000750,-0.000850,3.000000,1.000000,0.000000
75%,NaN,NaN,0.640000,7.470000,415.000000,34.400000,19.000000,13.000000,0.735000,8.930000,...,0.012900,0.011675,0.011875,0.013300,0.013300,0.014700,0.012975,3.000000,1.000000,0.000000
max,NaN,NaN,0.770000,12.150000,545.000000,49.200000,52.000000,40.000000,1.400000,26.990000,...,0.072200,0.065000,0.083000,0.071300,0.091400,0.060200,0.061700,3.000000,1.000000,1.000000

In [11]:
df2.head(10)

,IID,id,id_muestra_det,ast_pv,alt_pv,crea_pv,homo_pv,vb12_pv,acfol_pv,ast_dx,...,PC4,PC5,PC6,PC7,PC8,PC9,PC10,_merge,aim_118,aim_32
0,NaN,HG122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
1,CM264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1
2,CM266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1
3,CM267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1
4,CM271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1
5,CM272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1
6,CM273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1
7,CM275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1
8,CM277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1
9,CM279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,1

In [12]:
df2.tail(10)

,IID,id,id_muestra_det,ast_pv,alt_pv,crea_pv,homo_pv,vb12_pv,acfol_pv,ast_dx,...,PC4,PC5,PC6,PC7,PC8,PC9,PC10,_merge,aim_118,aim_32
1013,DG98W88,GC114,GC114,NaN,NaN,NaN,NaN,NaN,NaN,26.0,...,0.0076,-0.0102,0.0092,0.0263,0.0035,0.0400,-0.0168,3,1,0
1014,DG99B99,GD166,GD166,NaN,NaN,NaN,NaN,NaN,NaN,21.0,...,-0.0088,0.0012,-0.0517,-0.0144,-0.0306,-0.0038,0.0179,3,1,0
1015,DG99C21,GC15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.0350,-0.0235,0.0300,-0.0123,0.0095,-0.0012,0.0134,3,1,0
1016,DG99E22,GC131,GC131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0030,0.0082,-0.0251,0.0128,-0.0312,-0.0228,-0.0496,3,1,0
1017,DG99G31,CM077,CM077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.0225,-0.0078,-0.0321,-0.0046,0.0240,-0.0149,-0.0002,3,1,0
1018,DG99I41,HN05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.0072,-0.0062,0.0128,0.0381,0.0319,-0.0014,0.0072,3,1,0
1019,DG99L64,GC95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0109,0.0096,0.0152,-0.0325,0.0372,0.0072,-0.0018,3,1,0
1020,DG99R72,GC190,GC190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.0287,-0.0314,-0.0032,-0.0028,0.0059,0.0089,-0.0190,3,1,0
1021,DG99V27,HG085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0106,-0.0283,-0.0114,0.0003,0.0172,0.0025,-0.0135,3,1,0
1022,DG99Z36,HN276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0247,-0.0082,0.0069,-0.0108,-0.0060,-0.0173,-0.0139,3,1,0

##### ydata-profiling

In [13]:
profile2 = ProfileReport(
    df2,
    title="Profiling Report for df2",
    # explorative=True,
    minimal=True,
)
profile2.to_file("data/reports/profile2_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
# profile2.to_notebook_iframe()

##### sweetviz

In [30]:
"""
    Posibles target_feat indicados:
        modo_parto
        sdg_parto
        termino_rn
        macrosomia_rn
"""

sv_df2 = df1.astype(
    {
        "registro": "str",
        "fur": "str", # fecha
        "fecha_encuesta": "str", # fecha
        "fecha_muestra": "str", # fecha
        "Fecha_ev1": "str", # fecha
        "AcFolico_marca": "str", # nombre
        "f_encCTOG": "str", # fecha
        "fecha_muestraCTOG": "str" # fecha
    },
    copy=True
)

cols_to_numeric = [
    "sdg_dx",
    "gluc_pp_60",
    "ant_macrosomico",
    "sexo_rn",
    "peso_rn",
    "talla_rn",
    "pc",
    "capurro",
    "apgar_1",
    "apgar_5",
    "pH_A",
    "pO2_A",
    "pCO2_A",
    "pH_V",
    "pO2_V",
    "pCO2_V",
    "macrosomia_rn",
    "percentil_peso",
    "peso_placenta",
    "ins_cordon_parto",
    "e2_cordon_parto",
    "lep_cordon_parto",
    "adipo_cordon_parto",
    "ins_pp",
    "gluc_pp",
    "crea_pp",
    "urico_pp",
    "tg_pp",
    "ct_pp",
    "hdl_pp",
    "ldl_pp",
    "apob_pp",
    "lep_pp",
    "adipo_pp",
    "pcr_pp",
    "pgn_pp",
    "e2_pp",
    "SDG_ev1",
    "Folato_R24Hmcg",
    "FFQ_FOLATOmcg",
    "FFQ_DFE",
    "FFQ_energia",
    "AcFolico_supl",
    "AcFsup_dosis_mg",
    "PCT_1av",
    "DFE_R24H2",
]

for col in cols_to_numeric:
    sv_df2[col] = pd.to_numeric(sv_df2[col], errors="coerce")

report2 = sv.analyze(
    sv_df2,
    # target_feat="termino_rn", # comentando porque hay que eliminar NA"s primero
    pairwise_analysis="off", # apagando porque sv se queja en modo auto 
    # verbosity="progress_only", # no funciona todavía?
)

                                             |          | [  0%]   00:00 -> (? left)

In [31]:
report2.show_html(
    filepath="data/reports/sv_report2.html",
    open_browser=False,
)

Report data/reports/sv_report2.html was generated.